server {
    listen 9011;
    
    # 1. Servir la aplicación Angular
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto es vital para que las rutas de Angular funcionen al recargar
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy inverso hacia el Backend
    location /api/ {
        # Aquí usamos el NOMBRE DEL SERVICIO que definiste en docker-compose
        # Nginx (dentro de Docker) sí ve a 'keppler-api'
        proxy_pass http://keppler-api:9010/; 
        
        # Cabeceras estándar para proxies
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}