services:
  # Base de Datos de Satélites
  keppler-db:
    image: postgres:15-alpine
    container_name: keppler-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - keppler_db_data:/var/lib/postgresql/data
    networks:
      - keppler-network

  # Microservicio Ingestor (Python)
  keppler-ingestor:
    build:
      context: ./keppler-ingestor
      dockerfile: Dockerfile
    container_name: keppler-ingestor
    depends_on:
      - keppler-db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TLE_URL=${TLE_URL}
    restart: unless-stopped
    networks:
      - keppler-network

  # Microservicio API (Node.js)
  keppler-api:
    build: ./keppler-api-rest
    container_name: keppler-api
    depends_on:
      - keppler-db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${API_PORT}:9010"
    networks:
      - keppler-network
    restart: unless-stopped

  # Microservicio Frontend (Vite + React)
  keppler-frontend:
    build: ./keppler-frontend
    container_name: keppler-frontend
    ports:
      - "${FRONTEND_PORT}:9011"
    depends_on:
      - keppler-api
    environment:
      - API_URL=${API_URL}
    networks:
      - keppler-network
    restart: unless-stopped

# Definición de volúmenes para persistencia de datos
volumes:
  keppler_db_data:

# Red interna para comunicación entre microservicios
networks:
  keppler-network:
    driver: bridge